# Generated by Django 5.2 on 2025-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('worker', 'Worker')], default='user', max_length=50),
        ),
    ]
