# Generated by Django 5.2 on 2025-04-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
    ]
