# Generated by Django 5.2 on 2025-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
