# Generated by Django 5.2 on 2025-04-14 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='project.job')),
                ('job_seekers', models.ManyToManyField(limit_choices_to={'is_worker': True}, related_name='accepted_jobs', to='project.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
