# Generated by Django 5.2 on 2025-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_jobacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='works',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
