# Generated by Django 5.2 on 2025-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_user_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='works',
            field=models.IntegerField(default=0),
        ),
    ]
