# Generated by Django 5.2 on 2025-04-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='client',
            new_name='user',
        ),
    ]
