# Generated by Django 5.2 on 2025-04-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_job_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobacceptance',
            name='assigned_to',
            field=models.ForeignKey(db_column='acceptance_worker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job', to='project.user'),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='job_worker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='project.user'),
        ),
    ]
