# Generated by Django 5.2 on 2025-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_jobacceptance_assigned_to_alter_job_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
