# Generated by Django 5.2 on 2025-04-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_job_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
