# Generated by Django 5.2 on 2025-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
