# Generated by Django 5.2 on 2025-04-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin Registration Code',
                'verbose_name_plural': 'Admin Registration Codes',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('worker', 'Worker'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
