# Generated by Django 5.2 on 2025-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_adminregistrationcode_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highest_qualification',
        ),
        migrations.AddField(
            model_name='user',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='qualification_certificates/'),
        ),
    ]
