# Generated by Django 5.2 on 2025-04-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_user_highest_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_acceptances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_acceptances', to='project.jobacceptance'),
        ),
    ]
