# Generated by Django 5.2 on 2025-04-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_job_job_acceptances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_acceptances',
        ),
    ]
